# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0a0a0a, stop:0.3 #1a1a2e, stop:0.7 #16213e, stop:1 #0f3460);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QWidget {\n"
"    background: transparent;\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #00ffff;\n"
"    font-weight: bold;\n"
"    text-shadow: 0 0 10px #00ffff, 0 0 20px #00ffff;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background: rgba(0, 0, 0, 0.7);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    selection-background-color: #00ffff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #00ffff;\n"
"    box-shadow: 0 0 15px #00ffff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #00ffff;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    color: #ffffff;\n"
"    font-size: 11pt;\n"
"    line-height: 1.5;\n"
"    selection-background-color: #00ffff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #00ffff;\n"
"    box-shadow: 0 0 20px #00ffff;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 2px solid #00ffff;\n"
"    height: 8px;\n"
"    background: rgba(0, 0, 0, 0.7);\n"
"    border-radius: 4px;\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qradialgradient(cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #ffffff, stop:0.3 #00ffff, stop:1 #0080ff);\n"
"    border: 2px solid #00ffff;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -6px 0;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qradialgradient(cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #ffffff, stop:0.3 #00ffff, stop:1 #00ffff);\n"
"    box-shadow: 0 0 15px #00ffff, 0 0 25px #00ffff;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #1a1a2e, stop:1 #16213e);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 10px;\n"
"    padding: 12px 20px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 14pt;\n"
"    min-width: 30px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    color: #000000;\n"
"    box-shadow: 0 0 15px #00ffff, 0 0 25px #00ffff;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #0080ff, stop:1 #00ffff);\n"
"    border-color: #ffffff;\n"
"    box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgba(100, 100, 100, 0.3);\n"
"    border-color: #666666;\n"
"    color: #666666;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border-bottom: 2px solid #00ffff;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 8px 12px;\n"
"    border-radius: 4px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: rgba(0, 255, 255, 0.3);\n"
"    border: 1px solid #00ffff;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background: rgba(0, 255, 255, 0.5);\n"
"    border: 1px solid #00ffff;\n"
"}\n"
"\n"
"QMenu {\n"
"    background: rgba(0, 0, 0, 0.9);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background: transparent;\n"
"    padding: 8px 20px;\n"
"    border-radius: 4px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    color: #000000;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 transparent, stop:0.5 #00ffff, stop:1 transparent);\n"
"    margin: 5px 10px;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border-top: 2px solid #00ffff;\n"
"    color: #00ffff;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #1a1a2e, stop:1 #16213e);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    color: #000000;\n"
"    box-shadow: 0 0 15px #00ffff;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #0080ff, stop:1 #00ffff);\n"
"    border-color: #ffffff;\n"
"    box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background: rgba(100, 100, 100, 0.3);\n"
"    border-color: #666666;\n"
"    color: #666666;\n"
"}\n"
"\n"
"QListView {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: #ffffff;\n"
"    font-size: 11pt;\n"
"    selection-background-color: #00ffff;\n"
"    selection-color: #000000;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListView::item {\n"
"    background: transparent;\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background: rgba(0, 255, 255, 0.2);\n"
"    border: 1px solid #00ffff;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    color: #000000;\n"
"    font-weight: bold;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QListView::item:selected:active {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #0080ff, stop:1 #00ffff);\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background: #00ffff;\n"
"    width: 3px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background: #ffffff;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border-top: 2px solid #00ffff;\n"
"    color: #00ffff;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.catList = QtWidgets.QComboBox(parent=self.centralwidget)
        self.catList.setObjectName("catList")
        self.horizontalLayout_5.addWidget(self.catList)
        self.newCat = QtWidgets.QToolButton(parent=self.centralwidget)
        self.newCat.setObjectName("newCat")
        self.horizontalLayout_5.addWidget(self.newCat)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(0, 362))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.textsList = QtWidgets.QListView(parent=self.splitter)
        self.textsList.setObjectName("textsList")
        self.textBrowser = QtWidgets.QTextEdit(parent=self.splitter)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.VoicesList = QtWidgets.QComboBox(parent=self.centralwidget)
        self.VoicesList.setMinimumSize(QtCore.QSize(256, 0))
        self.VoicesList.setObjectName("VoicesList")
        self.horizontalLayout.addWidget(self.VoicesList)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ValueSpeed = QtWidgets.QSlider(parent=self.centralwidget)
        self.ValueSpeed.setMinimum(10)
        self.ValueSpeed.setMaximum(20)
        self.ValueSpeed.setPageStep(2)
        self.ValueSpeed.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ValueSpeed.setObjectName("ValueSpeed")
        self.horizontalLayout_2.addWidget(self.ValueSpeed)
        self.PrintValueSpeed = QtWidgets.QLabel(parent=self.centralwidget)
        self.PrintValueSpeed.setObjectName("PrintValueSpeed")
        self.horizontalLayout_2.addWidget(self.PrintValueSpeed)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BtnPrevious = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnPrevious.setMinimumSize(QtCore.QSize(74, 48))
        self.BtnPrevious.setMaximumSize(QtCore.QSize(78, 78))
        self.BtnPrevious.setObjectName("BtnPrevious")
        self.horizontalLayout_3.addWidget(self.BtnPrevious)
        self.BtnStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnStop.setMinimumSize(QtCore.QSize(74, 48))
        self.BtnStop.setMaximumSize(QtCore.QSize(78, 78))
        self.BtnStop.setObjectName("BtnStop")
        self.horizontalLayout_3.addWidget(self.BtnStop)
        self.BtnPausePlay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnPausePlay.setMinimumSize(QtCore.QSize(74, 48))
        self.BtnPausePlay.setMaximumSize(QtCore.QSize(78, 78))
        self.BtnPausePlay.setObjectName("BtnPausePlay")
        self.horizontalLayout_3.addWidget(self.BtnPausePlay)
        self.BtnNext = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnNext.setMinimumSize(QtCore.QSize(74, 48))
        self.BtnNext.setMaximumSize(QtCore.QSize(78, 78))
        self.BtnNext.setObjectName("BtnNext")
        self.horizontalLayout_3.addWidget(self.BtnNext)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ActOpen = QtGui.QAction(parent=MainWindow)
        self.ActOpen.setObjectName("ActOpen")
        self.ActExport = QtGui.QAction(parent=MainWindow)
        self.ActExport.setObjectName("ActExport")
        self.ActExit = QtGui.QAction(parent=MainWindow)
        self.ActExit.setObjectName("ActExit")
        self.ActAbout = QtGui.QAction(parent=MainWindow)
        self.ActAbout.setObjectName("ActAbout")
        self.menuFile.addAction(self.ActExport)
        self.menuHelp.addAction(self.ActAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Воспроизведение текста "))
        self.label_3.setText(_translate("MainWindow", "Категория:"))
        self.newCat.setToolTip(_translate("MainWindow", "Создать новую категорию (произведение)"))
        self.newCat.setText(_translate("MainWindow", "📝 Добавить категорию"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Введите текст здесь..."))
        self.label.setText(_translate("MainWindow", "Список голосов:"))
        self.label_2.setText(_translate("MainWindow", "Скорость воспроизведения:"))
        self.PrintValueSpeed.setText(_translate("MainWindow", "TextLabel"))
        self.BtnPrevious.setText(_translate("MainWindow", "⏪"))
        self.BtnStop.setText(_translate("MainWindow", "⏹️"))
        self.BtnPausePlay.setText(_translate("MainWindow", "⏯️"))
        self.BtnNext.setText(_translate("MainWindow", "⏩"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuHelp.setTitle(_translate("MainWindow", "Справка"))
        self.ActOpen.setText(_translate("MainWindow", "📂 Открыть"))
        self.ActOpen.setIconText(_translate("MainWindow", "📂 Открыть"))
        self.ActOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.ActExport.setText(_translate("MainWindow", "💾 Экспорт"))
        self.ActExport.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.ActExit.setText(_translate("MainWindow", "🚪 Выход"))
        self.ActExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.ActAbout.setText(_translate("MainWindow", "О программе 💡"))
