# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0a0a0a, stop:0.3 #1a1a2e, stop:0.7 #16213e, stop:1 #0f3460);\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QWidget {\n"
"    background: transparent;\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #00ffff;\n"
"    font-weight: bold;\n"
"    text-shadow: 0 0 10px #00ffff, 0 0 20px #00ffff;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background: rgba(0, 0, 0, 0.7);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    selection-background-color: #00ffff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #00ffff;\n"
"    box-shadow: 0 0 15px #00ffff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #00ffff;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    color: #ffffff;\n"
"    font-size: 11pt;\n"
"    line-height: 1.5;\n"
"    selection-background-color: #00ffff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #00ffff;\n"
"    box-shadow: 0 0 20px #00ffff;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 2px solid #00ffff;\n"
"    height: 8px;\n"
"    background: rgba(0, 0, 0, 0.7);\n"
"    border-radius: 4px;\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qradialgradient(cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #ffffff, stop:0.3 #00ffff, stop:1 #0080ff);\n"
"    border: 2px solid #00ffff;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -6px 0;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qradialgradient(cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"        stop:0 #ffffff, stop:0.3 #00ffff, stop:1 #00ffff);\n"
"    box-shadow: 0 0 15px #00ffff, 0 0 25px #00ffff;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #1a1a2e, stop:1 #16213e);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 10px;\n"
"    padding: 12px 20px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size: 14pt;\n"
"    min-width: 60px;\n"
"    min-height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    color: #000000;\n"
"    box-shadow: 0 0 15px #00ffff, 0 0 25px #00ffff;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #0080ff, stop:1 #00ffff);\n"
"    border-color: #ffffff;\n"
"    box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: rgba(100, 100, 100, 0.3);\n"
"    border-color: #666666;\n"
"    color: #666666;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border-bottom: 2px solid #00ffff;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 8px 12px;\n"
"    border-radius: 4px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: rgba(0, 255, 255, 0.3);\n"
"    border: 1px solid #00ffff;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background: rgba(0, 255, 255, 0.5);\n"
"    border: 1px solid #00ffff;\n"
"}\n"
"\n"
"QMenu {\n"
"    background: rgba(0, 0, 0, 0.9);\n"
"    border: 2px solid #00ffff;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background: transparent;\n"
"    padding: 8px 20px;\n"
"    border-radius: 4px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #00ffff, stop:1 #0080ff);\n"
"    color: #000000;\n"
"    box-shadow: 0 0 10px #00ffff;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 transparent, stop:0.5 #00ffff, stop:1 transparent);\n"
"    margin: 5px 10px;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    border-top: 2px solid #00ffff;\n"
"    color: #00ffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.VoicesList = QtWidgets.QComboBox(parent=self.centralwidget)
        self.VoicesList.setMinimumSize(QtCore.QSize(512, 0))
        self.VoicesList.setObjectName("VoicesList")
        self.horizontalLayout.addWidget(self.VoicesList)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ValueSpeed = QtWidgets.QSlider(parent=self.centralwidget)
        self.ValueSpeed.setMinimum(10)
        self.ValueSpeed.setMaximum(20)
        self.ValueSpeed.setPageStep(2)
        self.ValueSpeed.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ValueSpeed.setObjectName("ValueSpeed")
        self.horizontalLayout_2.addWidget(self.ValueSpeed)
        self.PrintValueSpeed = QtWidgets.QLabel(parent=self.centralwidget)
        self.PrintValueSpeed.setObjectName("PrintValueSpeed")
        self.horizontalLayout_2.addWidget(self.PrintValueSpeed)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BtnPrevious = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnPrevious.setObjectName("BtnPrevious")
        self.horizontalLayout_3.addWidget(self.BtnPrevious)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.BtnStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnStop.setObjectName("BtnStop")
        self.horizontalLayout_3.addWidget(self.BtnStop)
        self.BtnPausePlay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnPausePlay.setObjectName("BtnPausePlay")
        self.horizontalLayout_3.addWidget(self.BtnPausePlay)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.BtnNext = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnNext.setObjectName("BtnNext")
        self.horizontalLayout_3.addWidget(self.BtnNext)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ActOpen = QtGui.QAction(parent=MainWindow)
        self.ActOpen.setObjectName("ActOpen")
        self.ActSave = QtGui.QAction(parent=MainWindow)
        self.ActSave.setObjectName("ActSave")
        self.ActExit = QtGui.QAction(parent=MainWindow)
        self.ActExit.setObjectName("ActExit")
        self.actionCopy = QtGui.QAction(parent=MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(parent=MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelectAll = QtGui.QAction(parent=MainWindow)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.ActAbout = QtGui.QAction(parent=MainWindow)
        self.ActAbout.setObjectName("ActAbout")
        self.menuFile.addAction(self.ActOpen)
        self.menuFile.addAction(self.ActSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.ActExit)
        self.menuHelp.addAction(self.ActAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Воспроизведение текста "))
        self.label.setText(_translate("MainWindow", "Список голосов:"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Введите текст здесь..."))
        self.label_2.setText(_translate("MainWindow", "Скорость воспроизведения:"))
        self.PrintValueSpeed.setText(_translate("MainWindow", "TextLabel"))
        self.BtnPrevious.setText(_translate("MainWindow", "⏪"))
        self.BtnStop.setText(_translate("MainWindow", "⏹️"))
        self.BtnPausePlay.setText(_translate("MainWindow", "⏯️"))
        self.BtnNext.setText(_translate("MainWindow", "⏩"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuHelp.setTitle(_translate("MainWindow", "Справка"))
        self.ActOpen.setText(_translate("MainWindow", "📂 Открыть"))
        self.ActOpen.setIconText(_translate("MainWindow", "📂 Открыть"))
        self.ActOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.ActSave.setText(_translate("MainWindow", "💾 Сохранить"))
        self.ActSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.ActExit.setText(_translate("MainWindow", "🚪 Выход"))
        self.ActExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCopy.setText(_translate("MainWindow", "Копировать"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Вставить"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionSelectAll.setText(_translate("MainWindow", "Выделить все"))
        self.actionSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.ActAbout.setText(_translate("MainWindow", "О программе 💡"))
