name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Read version.py
        id: version_info
        run: |
          import re
          with open('version.py', 'r', encoding='utf-8') as f:
              content = f.read()

          def extract_var(var):
              match = re.search(rf'^{var}\s*=\s*[\'"]([^\'"]+)[\'"]', content, re.MULTILINE)
              print(match.group(1) if match else "")

          print("VERSION="+extract_var("VERSION"))
          print("VERSION_NAME="+extract_var("VERSION_NAME"))
          print("BUILD_DATE="+extract_var("BUILD_DATE"))
          print("AUTHOR="+extract_var("AUTHOR"))
          print("GITHUB_URL="+extract_var("GITHUB_URL"))
        shell: python
        # выводим для последующего использования

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile ^
            --name "Воспроизведение текста" ^
            --icon=main.ico ^
            --add-data "ui;ui" ^
            --hidden-import win32com ^
            --hidden-import win32com.client ^
            --hidden-import pythoncom ^
            main.py

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }} - ${{ steps.version_info.outputs.VERSION_NAME }}
          body: |
            Версия: ${{ steps.version_info.outputs.VERSION }}
            Дата сборки: ${{ steps.version_info.outputs.BUILD_DATE }}
            Автор: ${{ steps.version_info.outputs.AUTHOR }}
            Ссылка на репозиторий: ${{ steps.version_info.outputs.GITHUB_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/Воспроизведение текста.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
